version: '3.1'
services:
  itoken-config:
    image: 192.168.114.132:5000/itoken-zipkin
    restart: always
    container_name: itoken-zipkin
    ports:
      - 9411:9411
    networks:
      - zipkin_network
networks:
  zipkin_network: