version: '3.1'
services:
  itoken-config:
    image: 192.168.114.132:5000/itoken-admin
    restart: always
    container_name: itoken-admin
    ports:
      - 8084:8084
    networks:
      - admin_network
networks:
  admin_network: