version: '3.1'
services:
  itoken-config:
    image: 192.168.114.132:5000/itoken-config
    restart: always
    container_name: itoken-config
    ports:
      - 8888:8888
    networks:
      - config_network
networks:
  config_network: