version: '3.1'
services:
  itoken-eureka:
    image: 192.168.114.132:5000/itoken-eureka
    restart: always
    container_name: itoken-eureka
    ports:
      - 8761:8761
    networks:
      - eureka_network
networks:
  eureka_network: