version: '3.1'
services:
  itoken-config:
    image: 192.168.114.132:5000/itoken-zuul
    restart: always
    container_name: itoken-zuul
    ports:
      - 8769:8769
    networks:
      - zuul_network
networks:
  zuul_network: